### ISSUE TITLE
Metodos delete

### ISSUE THREAD

**Issue by MacoChave** [dadu0699/ESB-Documentation#3]
Como observación, los métodos delete no pueden recibir body, entonces sería bueno dejar en claro que se recibirá el id por query o por params...

`http://0.0.0.0:5001/team/7`

**Comment by dadu0699** [comment]
Que tal compañero. 
Fíjate que se dejó de esa manera respetando el documento original que definieron los coordinadores, y así respetar los avances de otros grupos. 

Te adjunto la documentación de MDN sobre el método [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) y un pequeño ejemplo de como podrías hacer la petición en Angular.
```ts
  public async deleteTeam(id_team: number): Promise<any> {
    const body = JSON.stringify({ id: id_team });
    const headers = new HttpHeaders().set('Content-Type', 'application/json');

    return await this._httpClient
      .delete(this.url, { body, headers })
      .toPromise();
  }
```
